export const reducerCases = {
  SET_USER: "SET_USER",
  CLEAR_USER: "CLEAR_USER",
  TOGGLE_LOGIN_MODAL: "TOGGLE_LOGIN_MODAL",
  CLOSE_AUTH_MODAL: "CLOSE_AUTH_MODAL",
  SET_SELLER: "SET_SELLER",
  SWITCH_MODE: "SWITCH_MODE",
  SET_SERVICE_DATA: "SET_SERVICE_DATA",
  HAS_USER_ORDERED_SERVICE: "HAS_USER_ORDERED_SERVICE",
  ADD_REVIEW: "ADD_REVIEW",
  TOGGLE_DARK_MODE: "TOGGLE_DARK_MODE",
  SET_DARK_MODE: "SET_DARK_MODE",
};
